### ISSUE TITLE
@rescript/tools depends on 'rescript@11.0.0-rc.4' 

### ISSUE THREAD

**Issue by mvaled** [cca-io/rescript-mui#204] opened 2023-11-20 18:13 UTC
I'm not sure whether or not this can create issues.  But given that rescript has both a runtime and a compiler, I think it might.

I'm facing a weird [issue](https://forum.rescript-lang.org/t/untagged-variant-detected-as-invalid-after-update-to-rc5/4875/3) trying to update the latest release of MUI, and I believe this might be related.

**Comment by mvaled** [comment] 2023-11-20 18:15
The repository: https://github.com/mvaled/r11rc5-mui shows the issue.

**Comment by fhammerschmidt** [comment] 2023-11-21 12:05
I only added it as a devDependency so this should not affect users. Your issue is caused by a compiler bug (as discussed in the forum) so will close this.

**Closed by fhammerschmidt** 2023-11-21 12:05 UTC
